version: '3'

volumes:
  minio:
  mysql-cfg:
  mysql-lib:

services:
  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
    volumes:
      - 'minio:/data'
    environment:
      MINIO_ACCESS_KEY: 'dev-access-key'
      MINIO_SECRET_KEY: 'dev-secret-key'
      MINIO_REGION_NAME: 'us-east-1'
    command: server /data # --certs-dir /etc/cert
    restart: 'unless-stopped'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: 'unless-stopped'

  mysql:
    image: 'mariadb:latest'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_DATABASE: 'shinpuru'
    volumes:
      - 'mysql-cfg:/etc/mysql'
      - 'mysql-lib:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
    restart: 'unless-stopped'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '18080:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: 'unless-stopped'
    depends_on:
      - 'mysql'
