version: '3'

services:
  traefik:
    image: 'traefik:latest'
    command:
      - '--providers.docker'
      - '--providers.file.directory=/etc/traefik/dynamic_conf'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--providers.docker.exposedByDefault=false'
      - "--certificatesResolvers.le.acme.email=support@mkbot.es" # ⚠️ <- enter your email here
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=http"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik/config:/etc/traefik/dynamic_conf'
    restart: always

  minio:
    image: 'minio/minio:latest'
    expose:
      - '9000'
    volumes:
      - './minio/data:/data'
    environment:
      MINIO_ACCESS_KEY: 'minio_access_key'
      MINIO_SECRET_KEY: 'minio_secret_key'
      MINIO_REGION_NAME: 'us-east-1'
    command: server /data # --certs-dir /etc/cert
    restart: always

  redis:
    image: 'redis:latest'
    expose:
      - '6379'
    restart: always

  mysql:
    image: 'mariadb:latest'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: shinpuru
    volumes:
      - './mysql/cfg:/etc/mysql'
      - './mysql/lib:/var/lib/mysql'
    restart: always

  shinpuru:
    image: 'ghcr.io/MK-Mods-OFC/Los-Templarios:latest'
    volumes:
      - './MK-Bot/config:/etc/config'
      - '/etc/cert:/etc/cert'
    expose:
      - '8080'
    environment:
      SP_VERSION: 6
      # Discord Config
      SP_DISCORD_TOKEN: OTc5NzQyODg3NDcyNDE4ODE2.GkidsY.BVVnxi0awt92fg_H0e0kQAzlfloo3eSn39fdZg
      SP_DISCORD_GENERALPREFIX: mkp!
      SP_DISCORD_OWNERID: "375276980028833792"
      SP_DISCORD_CLIENTID: "979742887472418816"
      SP_DISCORD_CLIENTSECRET: RxeUdtnQXywVu_u0duisdA-K7yZC71-X
      SP_DISCORD_GUILDSLIMIT: 0
      SP_DISCORD_GLOBALCOMMANDRATELIMIT_ENABLED: 1
      SP_DISCORD_GLOBALCOMMANDRATELIMIT_BURST: 3
      SP_DISCORD_GLOBALCOMMANDRATELIMIT_LIMITSECONDS: 20
      # Database
      SP_DATABASE_TYPE: mysql
      SP_DATABASE_MYSQL_HOST: mysql
      SP_DATABASE_MYSQL_USER: root
      SP_DATABASE_MYSQL_PASSWORD: mysql_root_password
      SP_DATABASE_MYSQL_DATABASE: shinpuru
      # Cache
      SP_CACHE_REDIS_ADDR: redis:6379
      SP_CACHE_REDIS_TYPE: 0
      SP_CACHE_CACHEDATABASE: 1
      # Logging
      SP_LOGGING_COMMANDLOGGING: 1
      SP_LOGGING_LOGLEVEL: 4
      # Storage
      SP_STORAGE_TYPE: minio
      SP_STORAGE_MINIO_ENDPOINT: minio:9000
      SP_STORAGE_MINIO_ACCESSKEY: minio_access_key
      SP_STORAGE_MINIO_ACCESSSECRET: minio_secret_key
      SP_STORAGE_MINIO_LOCATION: us-east-1
      SP_STORAGE_MINIO_SECURE: 0
      # Webserver
      SP_WEBSERVER_ENABLED: 1
      SP_WEBSERVER_ADDR: 0.0.0.0:8080
      SP_WEBSERVER_APITOKENKEY: <s]G's.[?zD}p$sJMJvr6k7,ZGma3A/RQ{jWk6vS7Kq{/\D.N-zLht_sEwG>/@\7
      SP_WEBSERVER_PUBLICADDR: http://bot.mkmods.space
      SP_WEBSERVER_RATELIMIT_ENABLED: 1
      SP_WEBSERVER_RATELIMIT_BURST: 50
      SP_WEBSERVER_RATELIMIT_LIMITSECONDS: 3
      SP_WEBSERVER_ACCESSTOKEN_LIFETIMESECONDS: 600
      SP_WEBSERVER_CAPTCHA_SITEKEY: 0fdd677f-a41b-45b4-a6a4-2a2353c2409c
      SP_WEBSERVER_CAPTCHA_SECRETKEY: 0xF932B110562B17696c6C5ed92907D0263C74954f
      # Codeexec
      SP_CODEEXEC_TYPE: "ranna"
      SP_CODEEXEC_RANNA_APIVERSION: "v1"
      SP_CODEEXEC_RANNA_ENDPOINT: "https://public.ranna.dev"
      SP_CODEEXEC_RATELIMIT_ENABLED: 1
      SP_CODEEXEC_RATELIMIT_BURST: 5
      SP_CODEEXEC_RATELIMIT_LIMITSECONDS: 60
      # Privacy
      SP_PRIVACY_NOTICEURL: "https://github.com/MK-Mods-OFC/Los-Templarios/blob/master/PRIVACY.md"
      SP_PRIVACY_CONTACT_0_TITLE: "E-Mail"
      SP_PRIVACY_CONTACT_0_VALUE: "support@mkbot.es"
      SP_PRIVACY_CONTACT_0_URL: "mailto:support@mkbot.es"
    restart: always
    depends_on:
      - mysql
      - redis
      - minio
    labels:
      traefik.enable: "true"
      traefik.http.routers.shinpuru.entrypoints: "https"
      traefik.http.routers.shinpuru.tls: "true"
      traefik.http.routers.shinpuru.tls.certresolver: "le"
      traefik.http.routers.shinpuru.rule: "Host(`bot.mkmods.space`)" # ⚠️ <- enter your domain here