name: Vulnerability Report
description: Report a security vulnerability.
labels:
  - bug
  - vulnerability
  - critical
assignees:
  - zekrotja
title: "⚠ "
body:
  - type: markdown
    attributes:
      value: |
        Hey, thank you very much for filling out this form to improve the project. ❤️
        ⚠ Please really only use this form to provide critical security vulnerabilities!
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: The type of the vulnerability.
      options:
        - Authorization Bypass
        - Impersonation
        - Permission Bypass
        - Dependency Related
        - Other REST API Related
        - Other Command Related
        - Other
  - type: checkboxes
    id: instances
    attributes:
      label: "Instances"
      description: On which instance(s) is the issue occuring?
      options:
        - label: "Canary"
          required: false
        - label: "Stable"
          required: false
        - label: "Self-Hosted"
          required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe here the vulnerability behavior as clear and concise as possible.
      placeholder: |
        The kick command can be executed without permission restriction.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Describe here in detail how to reproduce the issue.
      placeholder: |
        1. Remove all permissions from all roles.
        2. Execute a member kick.
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Here you can embed images, sketches, system logs or crash logs.
    validations:
      required: false

