name: Docker CD

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Populate info embeds
        run: bash ./ci/populateinfo.sh

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/heads/master')
        run: echo "TAG=latest" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/heads/dev')
        run: echo "TAG=canary" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/tags')
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          no-cache: true
          tags: |
            zekro/shinpuru:${{ env.TAG }}
            ghcr.io/MK-Mods-OFC/Los-Templarios:${{ env.TAG }}

      - name: Docker Remote Deploy
        if: ${{ env.TAG == 'canary' || env.TAG == 'latest' }}
        uses: appleboy/ssh-action@master
        with:
          host: zekro.de
          port: 2201
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/mgr/docker/core
            docker-compose pull shinpuru-${{ env.TAG }}
            docker-compose up -d shinpuru-${{ env.TAG }}
