name: Commands Wiki Generation

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'

jobs:
  wiki-generate:
    name: Wiki Generation
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: '1.18'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build and push to wiki
        run: |
          go run cmd/cmdman/v2/main.go -o ./docs/commandsManual.md
          git clone https://mkmods:${{ secrets.GITHUB_TOKEN }}@github.com/MK-Mods-OFC/Los-Templarios.wiki.git
          mv ./docs/commandsManual.md ./MK-Bot.wiki/Commands.md
          git -C ./MK-Bot.wiki add .
          git -C ./MK-Bot.wiki -c user.name="travis" -c user.email="travis" commit -m "automatically updated commands list"
          git -C ./MK-Bot.wiki push
